services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: bancobs2
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo_data:/data/db

  accountservice:
    build:
      context: ./AccountService
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://bancobs2:123456@mongo:27017/BankingDB
    depends_on:
      - mongo


  customerservice:
    build:
      context: ./CustomerService
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://bancobs2:123456@mongo:27017/BankingDB
    depends_on:
      - mongo

  loanservice:
    build:
      context: ./LoanService
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://bancobs2:123456@mongo:27017/BankingDB
    depends_on:
      - mongo

  transactionservice:
    build:
      context: ./TransactionService
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://bancobs2:123456@mongo:27017/BankingDB
    depends_on:
      - mongo
      - accountservice

volumes:
  mongo_data:
    driver: local